[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run migrate']

[start]
cmd = 'node server.js'

[health]
path = '/api/health'
interval = 10
timeout = 5
retries = 3
